# Generated by Django 3.0.5 on 2020-06-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.URLField()),
                ('email', models.EmailField(default=None, max_length=250, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=50, null=True)),
                ('job_role', models.CharField(default=None, max_length=50, null=True)),
                ('department', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Read_and_Write', 'Read_and_Write')], max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.User')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateTimeField(default=None, null=True)),
                ('reason', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('remarks', models.CharField(default=None, max_length=200, null=True)),
                ('access_level', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Read_and_Write', 'Read_and_Write')], max_length=50, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Item')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.User')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Resource'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(through='resource_management.Request', to='resource_management.User'),
        ),
    ]
